import type { Metadata } from "next";
import Navbar from "../../components/Navbar";
export const metadata: Metadata = {
  title: "About",
  description: "Generated by create next app",
};

function About() {
  return (
    <div>
      <Navbar />
      <h1 className="">About</h1>
    </div>
  );
}

export default About;